### ISSUE TITLE
Marketing page + release ideas

### ISSUE THREAD

**Issue by mattjared** [insurancezebra/sass-affected#7]
Should we build out a marketing page for this and utilize github pages or would you just want to use the README? Totally cool either way but I think we could `release` this to a few weekly newsletters and write a Medium piece about it to get some attention on it. Let me know if you want help with that or if that's a good use of time or not.

**Comment by johnapost** [comment]
This library is low-level enough where I'm not sure we will need to create any sort of page for it. Maybe we could with something that integrates into webpack or gulp build processes.

Also, I was hearing some chatter about an engineering blog being started. Perhaps we could just use that? @jasonhkennedy, do you know about that?
